package com.math3249.listler.util.message.Type

enum class MessageType {
    LIST_INSERTED,
    CATEGORY_IN_DATABASE,
    CATEGORY_INPUT_EMPTY,
    ITEM_IN_LIST,
    ITEM_NOT_IN_LIST,
    ITEM_NOT_IN_DATABASE,
    ITEM_INSERTED,
    ITEM_IN_DATABASE,
    ITEM_INPUT_EMPTY,
    ITEM_MISSING_CATEGORY,
    READ_MESSAGE;
}